RIOT-OS/rust-riot-sys

- src/lib.rs
This allows access that is probably UB in order to stay usable with
current nightly compilers. A better solution is needed, but the problem
is not new and this stops the alarms from hindering other work: It makes
riot-sys usable with recent nightlies (the default was switched from
warn to error some time between 2022-03-08 and 2022-04-25).
Creates: https://github.com/RIOT-OS/rust-riot-sys/issues/3
> Allow unaligned references for Debug implementations

- build.rs
This adds a marker that's needed for the https://github.com/RIOT-OS/RIOT/pull/17957 API change.
> Introduce coap_request_ctx_t marker

- Cargo.toml
- build.rs
- src/lib.rs
This closes https://github.com/RIOT-OS/rust-riot-sys/issues/3 by
* reverting the old workaround
* updating bindgen to 0.60.1 (thus not trying to derive(Debug) on the relevant types any more)
* blocking impl_debug from trying to implement Debug on some remaining offending types
This is, in theory, a regression in which traits types implement, but it doesn't affect anything through riot-wrappers, and generally just removes behavior that was unsafe before and is not likely to ever have been relied on.
The remaining workarounds can go away when https://github.com/rust-lang/rust-bindgen/issues/2221 is resolved, but don't do much harm if left for longer than that takes.
> Bindgen for packed structs (avoiding unaligned references)

- build.rs
This makes them less repetitive, and freezes a few markers' status to allow riot-wrappers to drop the relevant code after a minor release.
> markers: Cleanup

- Cargo.toml
A maintenance release that's primarily made to give riot-wrappers a guarantee about markers that can now be disregarded.
> Release 0.7.8

- .github/workflows/buildtest.yml
Currently, failures just look like this:
```
Building for native ... success.
Building for sltb001a ... failed!
Building for samr21-xpro ... failed!
```
This enables debug output, as it already was back on GitLab.
> CI: Make buildtest more verbose

- build.rs
https://github.com/RIOT-OS/RIOT/pull/18619 will change a static-ness of a mutex function ... more concretely, it's exposing an already existing flippy-floppiness. This should fix it.
Testing: I haven't tried this out yet, but CI will tell me the same things.
> build: Add mutex_lock to inline-or-not list

- .github/workflows/buildtest.yml
Otherwise, in some cases, the override established in CI will be ignored fully, and the older release would be used instead.
---
This was picked out of https://github.com/RIOT-OS/rust-riot-wrappers/pull/14
> CI: Update not only riot-* but also its dependencies

- Cargo.toml
Changes:
* `mutex_lock` function is now in the toplevel_from_inline list, making it usable no matter whether it is a static inline function or not
* README extended by note on versioning
---
Procedurally, I plan to wait for this to run through, some riot-rs to be published (even if just as a placeholder), to `cargo publish`, and then merge this fast-forwardly.
> Bump version to 0.7.9

- README.md
- build.rs
- src/lib.rs
* Remove obsolete C2Rust stuff
* Move what used to be comments (but is becoming really important, giving that RIOT APIs evolve while riot-wrappers goes for stability) into actual docs
> Documentation updates

- build.rs
This makes a build time assertion on the signature being (on the C side) compatible with a single unsigned value. For many types that's a property documented in C tests; for the others, it's conjecture that is aligned with their general perception.
Contributes-To: https://github.com/RIOT-OS/rust-riot-wrappers/issues/37
> Export `macro_XXX_DEV` macros (I2C_DEV)

- riot-headers.h
This will enable Rust applications to insert themselves into the auto init sequence without the need to go through C files.
> Add auto_init_utils.h

- build.rs
This item was missed because it doesn't follow the XXX_DEV pattern used by other peripherals.
See-Also: https://github.com/RIOT-OS/rust-riot-sys/pull/17
Contributes-To: https://github.com/RIOT-OS/rust-riot-wrappers/pull/36
> export macro_DAC_LINE

- src/bindgen.rs
Doxygen doesn't do these, and as long as C2Rust doesn't translate (and transpile??) Doxygen comments, these are just noise. The intra-docs links come from `@param[in] foo The Foo`.
> doc: Suppress warnings about things C2Rust does not uphold

- build.rs
- src/inline.rs
* Add netq_t which comes in when building with tinydtls
* Protect by making them unreasonably sized
I'll give that a test run on CI; generally, any breakage shown there is something where I'd investigate whether things were already subtly broken previously.
> Extern types: Add netq_t, make them large

- build.rs
- src/inline.rs
So far, we maintained a list of extern types that fall out of C2Rust compilation (typically deep in structs we never allocate, so we don't really *need* to know their properties). These types are already defined in such a way that we can't ever allocate them, but would only use them through pointers if at all.
This list was manually maintained and updated whenever something new popped up, typically through some libc.
This PR changes that to recognize extern types from the C2Rust output, and create replacement types on demand. In particular, this should fix an issue when types of the previously encoded names are not extern types on a particular platform, eg `__lock` in #20.
@Remmirad, could you review this? Does your `__lock` issue in #20 go away when applying this (even if you disable the …
> extern-types: Generate replacement types dynamically

- riot-headers.h
This is the first step to add support for wolfSSL in Rust on RIOT-OS. This has been tested using DTLS 1.3 and using SHA256. There is a work-in-progress wrapper that this sets the base for.
> wolfSSL support added

- Cargo.toml
- build.rs
This fixes issues when compiling with LLVM 16. New features (in particular the static function wrappers) are yet unused.
Thanks @maribu for reporting and the initial testing.
> bindgen: Use 0.64

- riot-headers.h
Needed for https://github.com/RIOT-OS/rust-riot-wrappers/pull/54
> Add `random` module to `riot-headers`

- build.rs
The algorithm for building the consensus CFLAGS was flawed in that the special-casing of `-I path` options only succeeded if the given option was in the first entry of the compile commands list.
While the algorithm can certainly need an overhaul, this is the minimally intrusive fix.
> build: Fix randomly missing -I entries

- Cargo.toml
Marking the version currently being pulled into RIOT in https://github.com/RIOT-OS/RIOT/pull/20303
Changes:
* Add macro support for ADC_LINE, DAC_LINE, I2C_DEV, PWM_DEV, QDEC_DEV, SPI_DEV, TIMER_DEV, UART_DEV.
* Added includes:
* auto_init_utils.h
* random.h
* riotboot/slot.h
* suit.h / suit/*
* uuid.h
* wolfssl/*
* Dynamically generate extern-types.
* Deprecate markers in favor of an exported BINDGEN_OUTPUT_FILE.
* Documentation updates.
* Update bindgen.
* Fix processing of compile-commands.json.
> Bump version to 0.7.10

- Cargo.toml
- README.md
- build.rs
- src/lib.rs
These are the non-breaking parts of #38.
> Small build system updates, make RIOT_USEMODULE optional

- build.rs
It's not pretty, but I do plan to reduce the amount of c2rust code anyway, and then this would go away again. (Because vprintf should really not be one of our exported functions).
This is the only error left on Rust for 64bit hosts after https://github.com/RIOT-OS/RIOT/pull/20315
> Add workaround for VaList being generated in v(f)printf

- Cargo.toml
The current HEAD has been used in RIOT for some time.
> Release v0.7.11

- .github/workflows/formal.yml
Nightlies can not have some components, eg. fmt (which caused trouble with https://github.com/RIOT-OS/rust-riot-sys/pull/41), so let's use stable instead. (We're not using any nightly fmt features).
> CI: Don't use nightly for fmt or readme

- .github/workflows/formal.yml
- riot-headers.h
These were already conditionally included, but it is unclear which transitive dependency triggered that.
This increases the required RIOT version to something around 2024.01, because https://github.com/RIOT-OS/RIOT/pull/19969 added sha512 support – that's well within the riot-sys stability guarantees.
> headers: Add hashes

- Cargo.toml
Changes:
* Add headers for hash functions
Waiting for https://github.com/RIOT-OS/RIOT/pull/20489 where those receive the extra testing of the full RIOT CI
> Release 0.7.12

- build.rs
This adds infrastructure to expose the LEDn_IS_PRESENT macro, and exposes the macro itself.
> LEDs: Expose presence

- riot-headers.h
This helps https://github.com/RIOT-OS/rust-riot-wrappers/pull/128 also implement core::error::Error
> headers: Add tiny_strerror

- riot-headers.h
It's a simple module gated added header file.
It is excluded from C2Rust visibility because it contains variadic functions ... and we should move off C2Rust unless needed anyway.
> headers: Add nimble_autoadv

- riot-headers.h
xtimer, in a static function, uses `_div_round_up` which is implemented using C11 generics.
As a general rule we should make c2rust more opt-in than opt-out (providing concrete known translatable functions rather than a catch-all conversion), but for now, this should solve the issue.
> headers: Don't let C2Rust process xtimer

- riot-headers.h
Not including it for C2Rust just to keep small the API surface that we'll ditch when making C2Rust opt-in by header.
> headers: Add ztimer64

- .github/workflows/buildtest.yml
As follow-up of https://github.com/RIOT-OS/RIOT/pull/21135 and https://github.com/RIOT-OS/RIOT/pull/21221
(Note that the workflow is expected to fail until the latter PR is merged)
> buildtest.yml: update links to RIOT examples

- build.rs
- riot-c2rust.h
Debugging https://github.com/RIOT-OS/RIOT/issues/21079 was a bit of a mess because C2Rust, at least on unhappy paths, sometimes prints errors that it doesn't really treat as critical. Those get ignored (because cargo doesn't even show those outputs), but then when something goes wrong in C2Rust, they send the user on a fool's errand. Fixing those I found while debugging it to not have to see them again.
Both fixes have extra comments that should keep me from going "do we really need that? \*tries rebuilding\* still works, we can strip that out!!!elf" later.
> Handle non-ciritcal-but-printed errors

- .github/workflows/buildtest.yml
See-Also: https://github.com/RIOT-OS/RIOT/pull/21359
> CI: Use compile_like_murdock instead of buildtest

- .github/workflows/buildtest.yml
- Cargo.toml
- build.rs
This is a regular "let's not leave old dependencies around" update with no real changes.
Going to 0.70 would be great, but so far introduces breakage around the size of max_align_t (might be related to the new --override-abi switch).
> dep: Update bindgen to 0.69
